### ISSUE TITLE
Door state can invert on 2nd floor

### ISSUE THREAD

**Issue by paulkim26** [paulkim26/collab-museum#82] opened 2023-06-10 14:12 UTC
Door opens when away, closes when approaching it

<img width="739" alt="image" src="https://github.com/paulkim26/collab-museum/assets/45007945/a5928de6-4aee-4a3d-949f-6eeef7849893">

**Comment by paulkim26** [comment] 2023-06-10 14:13
I suggest no collider for unlocked doors

**Comment by wollo77** [comment] 2023-06-29 06:13
duplicate of #125

**Closed** 2023-06-29 11:07 UTC
Labels: bug, duplicate, Main Lobby / Atrium
